### ISSUE TITLE
Missing -hostaddr parameter

### ISSUE THREAD

**Issue by mad-ops** [flightaware/Pgtcl#14]
-hostaddr exists in the documentation as part of pg_connect: http://flightaware.github.io/Pgtcl/html/pgtcl-pgconnect.html

However the following occurs:

```
% package require Pgtcl
2.1.0
% pg_connect -hostaddr dummy
bad option "-hostaddr": must be -host, -port, -tty, -options, -user, -password, -conninfo, -connlist, -connhandle, or -async
%

**Comment by resuna** [comment]
I suspect you're mixing up new-style and old-style connection parameters. The "hostaddr" option (without the dash) is only in the new-style connection list format, not the old style dash options.



Old style

dbName

    The name of the database to connect to.
-host hostName

    The host name of the database server to connect to.
-port portNumber

    The TCP port number of the database server to connect to.
-tty tty

    A file or TTY for optional debug output from the server.
-options serverOptions

    Additional configuration options to pass to the server.
-connhandle connectionHandleName

    Name to use for the connection handle, instead of pgtcl generating the name automatically. Without the option, the name is auto-generated, prefixed with pgsql, and with a numeric id at the end. This gives the programmer control over the name of the connection handle.
-async bool

    Connect asyncronously if [bool] is true.

**Comment by bovine** [comment]
Closing, since this is working as documented.
