### ISSUE TITLE
configure.in still uses PGTCL_CONFIG_FLAGS

### ISSUE THREAD

**Issue by vonbane** [flightaware/Pgtcl#15]
I get the following error while running configure in the released Pgtcl-2.1.0.tar.gz.

./configure: line 6046: PGTCL_CONFIG_CFLAGS: command not found

aclocal.m4 has been changed to TEA_CONFIG_CFLAGS, but the configure.in still has PGTCL_CONFIG_CFLAGS.  The configure script has the "PGTCL_CONFIG_CFLAGS" in it which causes an error during configure.  I assume the configure.in should be changed to TEA_CONFIG_CFLAGS also?

I'm not that familiar with autoconf and such so this may not be what's wrong either.

**Comment by resuna** [comment]
I think the correct fix is to change aclocal.m4 instead, but I will investigate before committing.

**Comment by resuna** [comment]
OK, after digging through the code, the correct change was to remove PGTCL_CONFIG_CFLAGS from configure.in completely. TEA changed tcl.m4 so TEA_CONFIG_CFLAGS was being called from TEA_ENABLE_SYMBOLS, so aclocal.m4 had to use the name TEA_CONFIG_CFLAGS and override the one from tcl.m4. *_CONFIG_CFLAGS is never explicitly called from configure.in at all.

**Comment by resuna** [comment]
Fixed in Pgtcl v2.1.1
