### ISSUE TITLE
Extend regexp in pgtcl-9.1 test to match current PostgreSQL versions

### ISSUE THREAD

**Issue by Mno-hime** [flightaware/Pgtcl#27]
I run `tclsh pgtcl.test` on OpenIndiana with PostgreSQL 9.4.20 and the `pgtcl-9.1` test fails with:

```
---- Result was:
1 0
---- Result should have been (exact matching):
1 1
==== pgtcl-9.1 FAILED
```

I seems that the regexp `lappend res [regexp {(7|8|9)0([0-9])[01]([0-9])} $val]` should be extended to match `90420` which comes out of both `pg::dbinfo version $conn` and `$conn version`.

Other currently supported versions of PostgreSQL (https://www.postgresql.org/about/news/1905/) should be added as well (likely 11.1, 10.6, 9.4.20, and 9.3.25).

**Comment by resuna** [comment]
That part of the test should either be removed or automatically generated.

**Comment by resuna** [comment]
For the moment I have extended the pattern through Tcl 12.
