### ISSUE TITLE
make install fails due to missing docs

### ISSUE THREAD

**Issue by bovine** [flightaware/Pgtcl#3]
Although it's harmless because the installation of the docs is the last thing done, it might still be disconcerting to a new user:

<pre>
jeff.lawson@owell:~/Pgtcl % sudo make install
If you have documentation to create, place the commands to
build the docs in the 'doc:' target.  For example:
        xml2nroff sample.xml > sample.n
        xml2html sample.xml > sample.html
 /bin/sh ./tclconfig/install-sh -c libpgtcl1.9.so /usr/local/lib/pgtcl1.9/libpgtcl1.9.so
 : /usr/local/lib/pgtcl1.9/libpgtcl1.9.so
 Install postgres-helpers.tcl /usr/local/lib/pgtcl1.9/postgres-helpers.tcl
 Install pkgIndex.tcl /usr/local/lib/pgtcl1.9
Installing header files in /usr/local/include
Installing ./generic/libpgtcl.h
Installing documentation in /usr/local/share/man
Installing ./doc/*.n
./tclconfig/install-sh: ./doc/*.n does not exist.
*** Error code 1

Stop.
make: stopped in /usr/home/jeff.lawson/Pgtcl
</pre>

**Comment by artem-exd** [comment]
how to install have the same error
`If you have documentation to create, place the commands to
build the docs in the 'doc:' target.  For example:
        xml2nroff sample.xml > sample.n
        xml2html sample.xml > sample.html
 /bin/sh ./tclconfig/install-sh -c libpgtcl1.9.dylib /Library/Tcl/lib/pgtcl1.9/libpgtcl1.9.dylib
 : /Library/Tcl/lib/pgtcl1.9/libpgtcl1.9.dylib
 Install postgres-helpers.tcl /Library/Tcl/lib/pgtcl1.9/postgres-helpers.tcl
 Install pkgIndex.tcl /Library/Tcl/lib/pgtcl1.9
Installing header files in /Library/Tcl/include
Installing ./generic/libpgtcl.h
Installing documentation in /Library/Tcl/share/man
Installing ./doc/*.n
./tclconfig/install-sh: ./doc/*.n does not exist.
make: *** [install-doc] Error 1
`

**Comment by bovine** [comment]
You don't need to do anything. It has already been installed. The documentation errors occur after the library installation is completed.

**Comment by artem-exd** [comment]
but I still don't have it
```
artems-mbp:flightaware-Pgtcl-a9d72ea artem$ tclsh
% package require Pgtcl
can't find package Pgtcl
% 
```

**Comment by bovine** [comment]
You may need to do:
```
lappend auto_path /Library/Tcl/lib
package require Pgtcl
```
See http://wiki.tcl.tk/1628

**Comment by artem-exd** [comment]
thank you so mutch!
