### ISSUE TITLE
osx job failing with "The job exceeded the maximum time limit for jobs, and has been terminated."

### ISSUE THREAD

**Issue by dthadi3** [flightaware/Pgtcl#38]
Hi,

I had added ppc64le(Linux on Power) architecture support on Travis-CI. For simplify testing later when distributions are re-building and re-releasing. But before going to that I'm facing some issue with the osx job on AMD64, could you please look into it.

Build logs for your reference: https://travis-ci.com/github/dthadi3/Pgtcl/builds/206962470

Regards,
Devendra

**Comment by resuna** [comment]
Looks like a transient problem getting to www.gaia-gis.it for libspatialite.

**Comment by bovine** [comment]
Closing, since we have migrated CI from Travis to Github Actions. Re-open if you are still having problems with that.
