### ISSUE TITLE
Consider changing behavior of pg_quote regarding NULL values

### ISSUE THREAD

**Issue by bovine** [flightaware/Pgtcl#6]
It's been expressed by @mutability that the behavior of pg_quote changes significantly when a database handle is also specified. 

``pg_quote ""`` returns ""

However, ``pg_quote $::asdidb ""`` returns "NULL"

"pg_quote if the connection handle is passed as an argument, the string is examined to see if it matches the null value string defined in the connection and if it is, NULL is returned, unquoted"

Although this behavior is documented, it is unexpected. (it is really counterintuitive that passing a db handle fundamentally changes what pg_quote does. more specifically, I'd expect "pg_quote $foo" and "pg_quote $db $foo" to act in the same way if you have not touched the settings of $db)

One possible option:  Change pg_quote to take a new flag (``pg_quote ?-null? ?db? value``) that would allow it to always return a "NULL" for a value of "" regardless of whether db were also supplied. If the flag is not supplied, then it will always return "" for a value of "" regardless of whether db were also supplied. This would be considered a breaking behavior change, but it seems like it might be worthwhile to include in the 2.0.0 release in order to normalize the behavior.

**Comment by resuna** [comment]
The description I added to the updated documentation reads:

_If a connection is provided, the connection is used to customize the quoting for the database referenced by the connection. Currently this only controls the null string used when the string is empty._ 

This seems to describe the current behavior in a non-confusing way.
