### ISSUE TITLE
Generate manpage version of documentation

### ISSUE THREAD

**Issue by bovine** [flightaware/Pgtcl#8]
See if it is somehow possible to generate manpages automatically from the current sgml documentation.

There is a FreeBSD port called ``textproc/docbook-to-man`` but there might be other methods also.

**Comment by resuna** [comment]
I've fixed the typos in the sgml source and modified the Makefile to generate the html by default.

I am not currently able to generate the PDF.

**Comment by bovine** [comment]
Having an actual manpage (troff) version of the same document would still be preferable so that it can easily be read from the console.

**Comment by resuna** [comment]
Oh, got you. This is a *new* feature, not fixing the broken documentation generation for the stuff that already exists. Sorry.

**Comment by bovine** [comment]
Resolved by 2a3f23f79504bb8e9fb9ea7958a2ff54d6219000
